### ISSUE TITLE
Adding More Columns for capturing Other Important Details of the Vendor , Customer, Items

### ISSUE THREAD

**Issue by EFFICIENTCORPORATES** [arrobalytics/django-ledger#107]
The Ledger Currently captures the basic details of Vendor and Customer.. 

More fields can be added either through the creation of Mixins or directly to the model like below:

**Vendor Model:**
Banking Data (for making Payment), Sales Tax Related Data like Registration Number (for Returns Filing), More Correspondance Informations, 

**Customer Model:**
Similarly for the Customer, adding more relevant Columns , like Sales Tax Information 

**Items Model:**
Additional Fields can be added to capture the specifications of the items .

**Comment by elarroba** [comment]
@EFFICIENTCORPORATES what do you mean with "More Correspondence Information" on the Vendor Model?

**Comment by elarroba** [comment]
@EFFICIENTCORPORATES Can you give an example of a specification? On the ItemModel?

**Comment by elarroba** [comment]
Waiting on @EFFICIENTCORPORATES for more guidance on pending Model fields for implementation.
