### ISSUE TITLE
I can't install

### ISSUE THREAD

**Issue by hallarks54** [arrobalytics/django-ledger#125]
I can't install what I did, I don't have much python knowledge, which version to install and which packages to install. I'm trying on the Windows version, but I keep getting an error.

**Comment by hallarks54** [comment]
If I can do a simple installation, please specify linux etc.

**Comment by BerndCzech** [comment]
I have the same problem I can not follow the documentation. [Documentation](https://django-ledger.readthedocs.io/en/latest/installation.html) states:

`pip install django-ledger`

But anything beyond that is unclear to me, where should i put this:
```
INSTALLED_APPS = [
    ...
    'django_ledger',
    ...
]
```
and where can i find the `manage.py` that occurs later in the docs: `python manage.py migrate django-ledger`

Can´t we have some docker compose file or something setting this project up seems a little complicated to me. I i don´t mean a development set up I thought i can simply start some webserver when i follow the instruction.

**Comment by elarroba** [comment]
This project is a Django Application, which means you need working knowledge of the Django Web Framework in order to use it. 

I would recommend checking out their website and documentation before using Django Ledger

[Django Project](https://www.djangoproject.com)

**Comment by BerndCzech** [comment]
Ok that is a great hint. :) It is probably clear if you have that background.

Might be valuable for others in the internet as well and you could add some step 0 into your instruction to mention basic knowledge of the django project as preliminary requirement.

**Comment by elarroba** [comment]
@BerndCzech the name of the project reads:
**"An Accounting, Bookkeeping & Financial Analysis Engine for the Django Framework."**

I will however be extra clear on the README about this requirement.

Thanks!
