### ISSUE TITLE
A server error occurred.  Please contact the administrator.

### ISSUE THREAD

**Issue by 868jjm** [arrobalytics/django-ledger#145]
**Describe the bug**
After I install for development I usually get a bug "A server error occurred.  Please contact the administrator."
Trying to log into the home page.  

**To Reproduce**
Navigate to your projects directory.
Clone the repo from github and CD into project.
	git clone https://github.com/arrobalytics/django-ledger.git && cd django-ledger
Install PipEnv, if not already installed:
	pip install -U pipenv
Create virtual environment.
	pipenv install
If using a specific version of Python you may specify the path.

	pipenv install --python PATH_TO_INTERPRETER
Activate environment.
	pipenv shell
Apply migrations.
	python manage.py migrate
Create a Development Django user.
	python manage.py createsuperuser
Run development server.
	python manage.py runserver
Try to log in.

**Expected behavior**
I should of been able to log into the terminal

**Screenshots**
https://imgur.com/a/UALYhGc

**Desktop (please complete the following information):**
 -Windows 10
 -Chrome

**Comment by elarroba** [comment]
Please set your Django DEBUG option to True and post your output.
