### ISSUE TITLE
python manage.py runserver Not working.

### ISSUE THREAD

**Issue by 868jjm** [arrobalytics/django-ledger#146]
**Describe the bug**
After I Set Up Django Ledger for Development. I get to: 

python manage.py test django_ledger

And when I run it i get an error.
(django-ledger-rXgOjIEC) C:\Users\qwerty\Documents\django-ledger2\django-ledger>python manage.py test django_ledger
Traceback (most recent call last):
  File "C:\Users\qwerty\Documents\django-ledger2\django-ledger\manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\qwerty\Documents\django-ledger2\django-ledger\manage.py", line 22, in <module>
    main()
  File "C:\Users\qwerty\Documents\django-ledger2\django-ledger\manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

**To Reproduce**
1. Set Up Django Ledger for Development
2. Install tzdata yourself
3. Open CMD 
4. Use: python manage.py test django_ledger
5. See error: (django-ledger-rXgOjIEC) C:\Users\qwerty\Documents\django-ledger2\django-ledger>python manage.py test django_ledger
Traceback (most recent call last):
  File "C:\Users\qwerty\Documents\django-ledger2\django-ledger\manage.py", line 11, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\qwerty\Documents\django-ledger2\django-ledger\manage.py", line 22, in <module>
    main()
  File "C:\Users\qwerty\Documents\django-ledger2\django-ledger\manage.py", line 13, in main
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

**Expected behavior**
A working demo.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome

**Comment by elarroba** [comment]
Hello @868jjm ,

In looking at your logs it seems that your virtual environment is not correctly installed or is not activated.
I've updated the installation section so you can get a working project going.

https://github.com/arrobalytics/django-ledger#installation

Please let me know if this helps.
Miguel

**Comment by elarroba** [comment]
An update to the PurchaseOrderModel tests was required to fix this bug. You may wait until Branch v0.5.4.2 is merged into development or check it out to see changes.

**Comment by elarroba** [comment]
The PurchaseOrderModel tests need to be updated to accommodate some API changes. PR #149 fixes this bug and will be merged shortly. You may check out Branch v0.5.4.2 or wait until the development branch is updated.
