### ISSUE TITLE
The invite link for discord is invalid or expired

### ISSUE THREAD

**Issue by hstanev** [arrobalytics/django-ledger#150]
Hello all and thank you for django-ledger!

I am trying to join the discord channel by clicking on the "Join our Discord Channel [Here](https://discord.gg/PEugR227)" link, but discord says the invite has expired or is not valid.

**To Reproduce**
1. Go to https://django-ledger.readthedocs.io/en/develop/README.html
2. Click on 'HERE'
3. See error at discord

**Expected behavior**
I expected to become a member of django-ledger discord channel

**Screenshots**
![discord](https://github.com/arrobalytics/django-ledger/assets/1263266/93df68b1-ab22-4b5b-a95c-04ac7ff995d7)

**Comment by elarroba** [comment]
Hello, @hstanev thank you for letting me know. I will update the link!

**Comment by elarroba** [comment]
@hstanev the link has been updated. Please let me know if the issue was resolved.

**Comment by hstanev** [comment]
@elarroba it works fine now, thanks!
