### ISSUE TITLE
KeyError at /admin/django_ledger/entitymodel/<UUID>/change/

### ISSUE THREAD

**Issue by 3leches** [arrobalytics/django-ledger#173]
**Describe the bug**

Unable to add or modify Entities in the Django Admin.  Attempting to create or modify an entry results in the error:

```
KeyError at /admin/django_ledger/entitymodel/add/
"Key 'slug' not found in 'EntityModelForm'. Choices are: accrual_method, address_1, address_2, admin, city, country, default_coa, depth, email, fy_start_month, hidden, last_closing_date, meta, name, numchild, path, phone, picture, state, website, zip_code."
Request Method:	GET
Request URL:	http://127.0.0.1:8000/admin/django_ledger/entitymodel/add/
Django Version:	4.2.6
Exception Type:	KeyError
Exception Value:	
"Key 'slug' not found in 'EntityModelForm'. Choices are: accrual_method, address_1, address_2, admin, city, country, default_coa, depth, email, fy_start_month, hidden, last_closing_date, meta, name, numchild, path, phone, picture, state, website, zip_code."

```

**To Reproduce**
1. Run the dev server
2. Login to the Django admin in a browser
3. Click on `Add` next to Entities

**Expected behavior**
A form to manage entities

**Screenshots**
<img width="1056" alt="image" src="https://github.com/arrobalytics/django-ledger/assets/10608222/432d7531-56a4-401f-bee7-86bddc1514a3">

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome
 - Version latest

**Additional context**

Commenting out [line 38 here](https://github.com/arrobalytics/django-ledger/blob/develop/django_ledger/admin.py#L38) will allow the form to load, but I have not been able to figure out how to expose the slug field in the form.  I see that it is being added via abstract model mixin, but I'm unable to figure out how to make it available to `EntityModelForm`.

Thank you!

**Comment by elarroba** [comment]
#174 
Thank you. Entities are meant to be created through the **/entity/create/** endpoint.
I will look at this.

**Comment by elarroba** [comment]
I am reworking the Admin app to make sure basic functionality exist to create and manage entities.
Functionality will be limited in the following version v0.5.5.5 but will continue to add features in future version.
