### ISSUE TITLE
docker compose file

### ISSUE THREAD

**Issue by simevo** [arrobalytics/django-ledger#176]
It would make it easier to try out django-ledger if a containerized set up was available. Either here or in https://github.com/arrobalytics/django-ledger-starter

Just `docker-compose up` then http://localhost:8000/ledger

I see this has been already brought up in the past (#125).

I am happy to contribute a setup similar to [this one](https://github.com/Arpapiemonte/weboll/blob/main/local.yml) with adminer service to access the DB.

**Comment by elarroba** [comment]
@simevo I just created a pull request for review... thanks for suggesting this.

**Comment by MateehUllah** [comment]
@elarroba I created PR kindly review it.
