### ISSUE TITLE
Discord-link not working / Chat-GPT writes nonsense

### ISSUE THREAD

**Issue by hemabe** [arrobalytics/django-ledger#179]
Hi,
I would like to access the discord-server but I get an error which says that the link is not valid anymore.

Then I tried to start with django-ledger, I'm totally new to this project. I wanted to test a few transactions/bookings 
and did not find anything in the documentation. So I asked ChatGPT and this is what I got:

```
from django_ledger.models.entity import EntityModel
from django_ledger.models.accounts import Account
from django_ledger.models.journalentry import JournalEntry, JournalEntryLine

entity = EntityModel.objects.get(name="Ihr Entity-Name")

account1 = Account.objects.get(name="Ihr Konto 1", entity=entity)
account2 = Account.objects.get(name="Ihr Konto 2", entity=entity)

journal_entry = JournalEntry(entity=entity, memo="Anpassung für vorherigen Eintrag")
journal_entry.save()

JournalEntryLine(journal_entry=journal_entry, account=account1, amount=100, is_debit=True).save()
JournalEntryLine(journal_entry=journal_entry, account=account2, amount=100, is_debit=False).save()
```

Could someone please help me and show me how this would look like correctly. Thanks!

**Comment by elarroba** [comment]
Hello @hemabe .
Did you check the [QuickStart Guide](https://github.com/arrobalytics/django-ledger/blob/develop/notebooks/QuickStart%20Notebook.ipynb)?
