### ISSUE TITLE
Admin Chart Of Accounts FieldError

### ISSUE THREAD

**Issue by 25-do** [arrobalytics/django-ledger#219]
Am getting a field error when i try to change a chart of account on the Admin panel 
`FieldError at /admin/django_ledger/chartofaccountmodel/db7b1212-b256-451c-a25a-ce142b2bc967/change/

Unknown field(s) (locked) specified for ChartOfAccountModel. Check fields/fieldsets/exclude attributes of class ChartOfAccountsModelAdmin.`

**Comment by tolland** [comment]
ChartOfAccountModel doesn't seem to have a "locked" attribute/field, so probably comment that out on line 111

**Comment by tolland** [comment]
https://github.com/arrobalytics/django-ledger/pull/220

**Comment by elarroba** [comment]
@25-do I believe this was resolved by #220
