### ISSUE TITLE
Next steps on this project

### ISSUE THREAD

**Issue by Marlysson** [arrobalytics/django-ledger#24]
That awesome project!! Really interesting.

Looking into Roadmap features looks good as new features. I'm looking how contribute with this project.. What's the next features that you plan to develop in this project?

**Comment by elarroba** [comment]
Hello @Marlysson. 

Thank you for your note. We are currently developing the roadmap for this project.
If you are interested, please subscribe to our email list at [djangoledger.com](https://www.djangoledger.com) for future communications on what's next. 
In the meantime, I will contact you via email for next steps on contributing to the project.

Regards,
Miguel
