### ISSUE TITLE
Include City, State/Province, Zip Code & Country as Separate Fields

### ISSUE THREAD

**Issue by elarroba** [arrobalytics/django-ledger#25]
- When creating an entity, an "address line 1" and "address line 2" row exists but "address line 2" is meant to receive City, State Zip info rather than what people often enter for "address line 2" which is a secondary address such as "Suite B".
- The default text says City, State Zip but the text color is faint so this message may be lost on some users.

**Comment by mnooel** [comment]
should we abstract this to an address class? Entities have an address, employees might need an address, vendors have an address.

**Comment by elarroba** [comment]
@mnooel There is a ContactInfoMixIn class already used by Vendor/Customer models. This class will be modified to incorporate this functionality.
