### ISSUE TITLE
Hello, can I use your project in the company's financial system?

### ISSUE THREAD

**Issue by robotw** [arrobalytics/django-ledger#38]
Hello, can I use your project in the company's financial system?
Do you have any major version updates recently?

**Comment by elarroba** [comment]
@robotw Thank you for your comment.

The purpose of this project is to provide the functionality and the engine necessary to run any financial system for any company/entity. However, this project is not stable and is under development. Please review our warning:

> WARNING: Currently this project is under active development and is not recommended for production environments. Breaking changes may occur in future releases. The author is actively working to provide a stable release as soon as possible and to incorporate the following functionality:

In the meantime, please review our current [ROADMAP](https://github.com/arrobalytics/django-ledger/blob/develop/ROADMAP.md) for more details. There's also other plans beyond v1.0 that we still need to define.

I am currently working on some of the new v0.4 features to be releases sometime in January 2021 time frame.
