### ISSUE TITLE
Adding products/services to the generated invoice

### ISSUE THREAD

**Issue by HasanAwada** [arrobalytics/django-ledger#41]
**Is your feature request related to a problem? Please describe.**

The project looks promising and we are interested in it, however, we are unable to create products/services and link them to generated invoice.

**Describe the solution you'd like**
We would like to know if this is part of your plan, and if yes, when to expect that to be delivered.

**Describe alternatives you've considered**
We are open to contribute in this part.

**Comment by elarroba** [comment]
@HasanAwada This feature is coming on version 0.4.0. Currently being developed (Bill/Invoice Item Support). 
Please take a look at the [ROADMAP](https://github.com/arrobalytics/django-ledger/blob/develop/ROADMAP.md) for more details.

**Comment by HasanAwada** [comment]
Thanks for your prompt reply. Is there a roughly speaking expected due date for the Engine & Data Modeling milestone?
