### ISSUE TITLE
Simple Error

### ISSUE THREAD

**Issue by 868jjm** [arrobalytics/django-ledger#48]
![error](https://user-images.githubusercontent.com/77506107/117651336-d7796a00-b15f-11eb-83e4-36ca822343f1.png)

im using VS2019 It seems like a simple issue. Not sure how to fix it.

**Comment by 868jjm** [comment]
![image](https://user-images.githubusercontent.com/77506107/117661354-40ff7580-b16c-11eb-926e-58711a5d81e5.png)

**Comment by elarroba** [comment]
@868jjm Please try again. I've removed the use_pipfile flag from the setup.py file.

**Comment by 868jjm** [comment]
![image](https://user-images.githubusercontent.com/77506107/133593575-1b23251f-0a2f-4927-a82d-4d4dcec2edbe.png) Still having some difficulty here.
