### ISSUE TITLE
Allow accurate simultaneous reporting as cash or accrual

### ISSUE THREAD

**Issue by Beachwood619** [arrobalytics/django-ledger#5]
from this article:

https://wffacpa.com/how-a-glaring-hole-in-quickbooks-online-makes-life-difficult-for-accrual-basis-companies-that-are-cash-basis-taxpayers-and-how-to-work-around-it/

"Quickbooks Online (“QBO”) does many things well. The improvements Intuit has brought to their cloud-based offering over the past few years have amounted to a near-total overhaul of what was originally an unusable replacement for the classic Quickbooks Desktop. That said, there is still (what I consider to be) a glaring hole in QBO at a basic, fundamental level: the inability to decide for ourselves if a journal entry should affect both accrual and cash basis reports or if it should only affect accrual basis reports. The lack of our ability to choose for ourselves makes it much more difficult to manage the books of a company who need to accurately track both cash basis and accrual basis figures."

"...cash basis taxpayers are still required to capitalize and depreciate fixed assets, and recording depreciation does not affect cash, but should affect cash basis reports."

I've spoken with two CPA's who have complained about the accrual vs cash reporting methods with Quickbooks.  One client's CPA adjusted the books and shows him making almost $400k more in income and we're not sure why she did that but I believe it has something to do this issue.  If this can be a standard feature that would really make it competitive.

**Comment by elarroba** [comment]
This functionality has been implemented as part of the LedgerPlugInMixIn
