### ISSUE TITLE
Documentation to use it as base for other projects

### ISSUE THREAD

**Issue by keinagae** [arrobalytics/django-ledger#52]
Is it possible to use django ledger as base for accounting in other software and is there any documentation present for this purpose

**Comment by mnooel** [comment]
No there is not. At the moment, we are developing a minimum viable product with the logic and rules required for a secure GAAP financial accounting system. We might develop API capabilities after our first stable release.  What would you like to see? What are the use cases? Please let us know so we make considerations for the future. Thanks for your interest. Please follow the project and let us know if you would like to join the team.

**Comment by keinagae** [comment]
We are currently developing a product for hospital  and for finances we are looking some prebuilt base to work on and came across this project and it looked mature enough for our use case as we need only core functionalities and for sale purchases we want it more generalized so thought if its possible to use it as base

**Comment by elarroba** [comment]
Documentation is now being hosted on [ReadTheDocs](https://django-ledger.readthedocs.io/en/latest/index.html).
Still a lot to document.
Any help is always welcome.
