### ISSUE TITLE
Cash Vs. Accrual invoicing/Bills features

### ISSUE THREAD

**Issue by Beachwood619** [arrobalytics/django-ledger#6]
Killer Feature:
The ability to create an invoice and accept payment and determine how to report in cash vs accrual.  E.g. Create an invoice for $12,000 and collect $12,000 but be able to show the $12,000 as a liability and then realize income on that invoice as the work is produced or on a set schedule or however you choose to realize it.  And also be able to show the invoice and payment as a cash basis reporting at the same time.

Workflow for this feature:
When this invoice is open it will show like this in the balance sheet:
Debit - AR(Asset Account)
Credit - Deferred Income(Liability Account)
 
Invoice is paid:
Debit - Cash
Credit - AR
*Invoice will no longer show up in the AR aging report

Then realize income from invoice:
Debit - Deferred Income
Credit - Income

You can do progress billing from this invoice or a set schedule of billing for this invoice.  Right now, Quickbooks does not offer this feature.  CPA's have to manually convert these numbers in a spreadsheet.  

Also, have the exact feature REVERSED for Bills and expenses, e.g. prepaid expenses for things like insurance paid up front for the entire year are then expensed out each month during the life of the policy.

**Comment by elarroba** [comment]
This issue has been addressed in the LedgerPlugInMixIn class.
InvoiceModel and BillModel make use of this new MixIn to implement functionality described by @Beachwood619.
Closing this issue.
