### ISSUE TITLE
Translations table?

### ISSUE THREAD

**Issue by platipusica** [arrobalytics/django-ledger#62]
Hi, 

any plans for internationalization? How do I get the list of ALL captions (messages?) used to start working on it?

thx

**Comment by elarroba** [comment]
Yes. It is part of the [Roadmap](https://github.com/arrobalytics/django-ledger/blob/develop/ROADMAP.md). However, not a big priority right now as UI and text can change quite a bit until v1.0.

**Comment by platipusica** [comment]
np
