### ISSUE TITLE
Logic behind UUID?

### ISSUE THREAD

**Issue by platipusica** [arrobalytics/django-ledger#64]
Hi all, 

I am puzzled with the logic for using uuid? Why not using auto increment?
Some notes about this easily found:
https://stackoverflow.com/questions/3936182/using-a-uuid-as-a-primary-key-in-django-models-generic-relations-impact

As I see it, ledger is not the App publicly available, so not quite sure what is it protected? It will be very difficult to manage in-house ledger. Just like I've found the Bill Temp FK, which can't be found that easily just by the look. 

If we look at Bill model, all xxx_id take way more space than all other fields combined. Lets try to sort this by sql!? Impossible task.

Just my 2c btw, your project tho

Thoughts?

**Comment by elarroba** [comment]
A good article on the subject.
[UUID or GUID as Primary Keys?](https://tomharrisonjr.com/uuid-or-guid-as-primary-keys-be-careful-7b2aa3dcb439)

**Comment by mnooel** [comment]
This is something that I have been thinking about too. Incremented pre-numbered records have been used as an internal control in accounting for a long time. Take for example checks, each with their own number auto-incrementing along a sequence. All forms of documentation and record-keeping were sequentially prenumbered before the move to electronic record keeping. If a check is missing in the sequence, the question arises from the auditor, "what happened to it". Voided or misprinted checks need to be retained by the treasury department for a period of a year to substantiate these gaps. The logic behind this is in a well-designed accounting department, records of a certain class [checks, vouchers, receipts, deposits, credit card charges, journal entries] should not break the sequence regularly. This is an indicator of a poorly operating accounting department and elevates the risk of error. So as an auditor, if I see a lot of gaps or missing elements in a sequence, I know that something is not working as it should be, and I increase my professional skepticism and substantive testing.

Auto-increment answers the question "are there gaps?". It does not answer, who what when where why. I don't think that auto-increment is absolutely needed as long as the system can report these gaps and the reasons/players in some fashion. There is also the consideration that some organizations, individuals, or whoever will not buy into DjangoLedger if auto-increment isn't a part of the system. My wife was in auditing and could speak more to that, I'll ask her.

I envision that if a record is to be deleted, a reason must be submitted by one user and approved by a manager or another person. this would satisfy the needed segregation of duties for proper internal controls. My other idea would be that records of a certain type have a regex-like id. Journal entries would be JE1, JE2, .....JE101. Vendor Vouchers would be VV1......VV101, etc. This would allow the records to be discernable by class and incrimented.

**Comment by platipusica** [comment]
Good stuff.

Cheers
